const teamMembers = [
  {
    name: "Radha Choudhary",
    title: "President",
    team: "Executive Body",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/Radha_Choudhary_President_and_Bluebird_Vice_Captain_hrmucl.jpg",
    description: "1",
    linkedin:
      "https://www.linkedin.com/in/radha-choudhary-990115377?utm_source=share_via&utm_content=profile&utm_medium=member_android",
  },
  {
    name: "Aayush Barik",
    title: "Vice President",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/Aayush_Barik_Vice_President_klgnid.jpg",
    description: "2",
    team: "Executive Body",
    linkedin: "https://www.linkedin.com/in/aayush-barik-668843339/",
  },
  {
    name: "Subhakanta Sahoo",
    title: "General Secretary",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/Subhakanta_Sahoo_General_Secretary_hpnft5.jpg",
    description: "3",
    team: "Executive Body",
    linkedin: "https://www.linkedin.com/in/subhakanta-sahoo-492079344/",
  },
  {
    name: "Aditya Padhi",
    title: "Treasurer",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/Aditya_Padhi_Treasure_1_1_mapdzr.jpg",
    description: "4",
    team: "Executive Body",
    linkedin: "https://www.linkedin.com/jobs/",
  },
  {
    name: "Ashirbad Roy",
    title: "Management Lead",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/ASHIRBAD_ROY_MANAGEMENT_LEAD_c7acqo.jpg",
    description: "5",
    team: "Executive Body",
    linkedin: "https://www.linkedin.com/in/ashirbad-roy-99978b394/",
  },
  {
    name: "Sahil Das",
    title: "Creative Lead",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/Sahil_Das__Design_Head_cbj1wt.jpg",
    description: "6",
    team: "Executive Body",
    linkedin: "https://www.linkedin.com/in/sahil-das-430222325/",
  },
  {
    name: "Tirthankar Mishra",
    title: "Captain",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/TirthankarMishra_BluestreakCaptain_bdgxsj.jpg",
    team: "Team Bluestreak",
    description: "7",
    linkedin: "https://www.linkedin.com/in/tirthankar-mishra025/",
  },
  {
    name: "Subhrajyoti Behera",
    title: "Vice Captain",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/Subhrajyoti_Behera_Bluestreak_Vice_Captain_kxyeqp.jpg",
    description: "8",
    team: "Team Bluestreak",
    linkedin: "https://www.linkedin.com/in/subhrajyoti-behera/",
  },
  {
    name: "Swagat Sibasish Mohanty",
    title: "Chassis Lead",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/Swagat_Sibasish_Mohanty_Chassis_Lead_a3cain.jpg",
    description: "9",
    team: "Team Bluestreak",
    linkedin: "https://www.linkedin.com/in/swagat-sibasish-mohanty-a7590b371/",
  },
  {
    name: "Ayushman Senapati",
    title: "Drivetrain Lead",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/Ayushman_Senapati_DT_lead_kcrkpo",
    description: "10",
    team: "Team Bluestreak",
    linkedin: "https://www.linkedin.com/in/ayushman-senapati-394a38274/",
  },
  {
    name: "Aman Routray",
    title: "Aero Dynamic Lead",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/AMAN_ROUTRAY__AERO_LEAD_sewlzi.jpg",
    description: "11",
    team: "Team Bluestreak",
    linkedin: "https://www.linkedin.com/in/aman-kumar-routray-907b17310/",
  },
  {
    name: "Gyandeep Nayak",
    title: "Vehicle Dynamics Lead",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/Gyandeep_Nayak_VD_Lead_x9kvgr.jpg",
    description: "12",
    team: "Team Bluestreak",
    linkedin: "https://www.linkedin.com/in/gyandeep-nayak-8a0a51354/",
  },
  {
    name: "Santosh Barik",
    title: "Captain",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/images_1_ujpf6e.jpg",
    description: "13",
    team: "Team Blueprint",
    linkedin: "https://www.linkedin.com/jobs/",
  },
  {
    name: "Soham Panigrahi",
    title: "Vice Captain",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/Soham_Panigrahi_VIce-captain_Team_BluePrint_5.0__page-0001_1_1_z1ntth.jpg",
    description: "14",
    team: "Team Blueprint",
    linkedin: "https://www.linkedin.com/in/soham-panigrahi-25a16737b/",
  },
  {
    name: "Priyabrata Acharya",
    title: "Analysis Lead",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/Priyabrata_Acharya___Blueprint_Analysis_Lead_page-0001_1_pgpnk8.jpg",
    description: "15",
    team: "Team Blueprint",
    linkedin: "https://www.linkedin.com/in/priyabrata-acharya-513a673a4/",
  },
  {
    name: "Subasis Swain",
    title: "Electonics Lead",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/images_1_ujpf6e.jpg",
    description: "16",
    team: "Team Blueprint",
    linkedin: "https://www.linkedin.com/in/subasis-swain-4a3227350/",
  },
  {
    name: "Subhakanta Sahoo",
    title: "CAD Lead",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/Subhakanta_Sahoo_General_Secretary_hpnft5.jpg",
    description: "17",
    team: "Team Blueprint",
    linkedin: "https://www.linkedin.com/in/subhakanta-sahoo-492079344/",
  },
  {
    name: "Yegnesh Sagar",
    title: "Captain",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/images_1_ujpf6e.jpg",
    description: "18",
    team: "Team Bluebird",
    linkedin: "https://www.linkedin.com/in/yegnesh-sagar-89778b348/",
  },
  {
    name: "Radha Choudhary",
    title: "Vice Captain",
    img: "https://res.cloudinary.com/ddoeahbpv/image/upload/Radha_Choudhary_President_and_Bluebird_Vice_Captain_hrmucl.jpg",
    description: "19",
    team: "Team Bluebird",
    linkedin:
      "https://www.linkedin.com/in/radha-choudhary-990115377?utm_source=share_via&utm_content=profile&utm_medium=member_android",
  },
];

export default teamMembers;
